# Makefile for CS5600 Assignment 2 - Command Line Arguments
# ZW / 9/16/2025
# This file compiles the C program and creates the executable.

CC = gcc          
CFLAGS = -Wall    

all: arger-wang  

arger-wang: arger-wang.c
	$(CC) $(CFLAGS) -o arger-wang arger-wang.c

clean:
	rm -f arger-wang

